module.exports = [
    { id: 1,
        item_name: "income",
        amount: 1000,
        date: "10-02-2023",
        from: "employer",
        category: "income",
      },
   { id: 2,
      item_name: "taxes",
      amount: -300,
      date: "10-05-2023",
      from: "income",
      category: "taxes",
   },
   { id:3,
       item_name: "retirement",
       amount: -200,
       date: "10-6-2023",
       from: "pet store",
       category: "retirement"
   },
   { id: 4,
        item_name: "savings",
        amount: -100,
        date: "10-7-2023",
        from: "savings",
        category: "savings"
      },
      { id: 5,
        item_name: "cc payment",
        amount: -100,
        date: "10-22-2023",
        from: "checking",
        category: "payment"
      },
      { id: 6,
        item_name: "birthday money",
        amount: 20,
        date: "10-10-2023",
        from: "income",
        category: "birthday money"
      },
      { id: 7,
        item_name: "coffee",
        amount: -4,
        date: "10-10-2023",
        from: "checking",
        category: "coffee"
      },
      { id: 8,
        item_name: "internet",
        amount: -100,
        date: "10-10-2023",
        from: "checking",
        category: "internet"
      },
      { id: 9,
        item_name: "groceries",
        amount: -76,
        date: "10-10-2023",
        from: "checking",
        category: "groceries"
      },
      { id: 10,
        item_name: "pet",
        amount: -7,
        date: "10-10-2023",
        from: "checking",
        category: "pet"
      },
    ]