module.exports = [
    { id: 1,
        item_name: "income",
        amount: 5000,
        date: "10-02-2023",
        from: "employer",
        category: "bank account",
      },
   { id: 2,
      item_name: "savings",
      amount: 3000,
      date: "10-05-2023",
      from: "income",
      category: "income",
   },
   { id:3,
       item_name: "monthly cat food",
       amount: 360,
       date: "10-6-2023",
       from: "pet store",
       category: "savings"
   },
   { id: 4,
        item_name: "monthly car insurance",
        amount: 150,
        date: "10-10-2023",
        from: "checking",
        category: "car insurance company"
      },
    ]